apiVersion: apps/v1
kind: Deployment
metadata:
  name: k9o-demo-backend-v2
  namespace: k9o-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: k9o-demo-backend
      version: v2
      env: dev
  template:
    metadata:
      labels:
        app: k9o-demo-backend
        version: v2
        env: dev
    spec:
      containers:
      - image: kvn0218/kuma-demo-be:latest
        name: kuma-be
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: TOTAL_OFFER
          value: "2"
        - name: REDIS_HOST
          value: redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001